### ISSUE TITLE
Create launch intent (welcome message)

### ISSUE THREAD

**Issue by sachin303** [kulwantyadav101/Team3-HackTheMachine#10]
Create launch intent which would handle request made through alexa when customer says "Launch greeter" to start our skill.

**Launch Content**
Hello {CustomerName}, Thank you for choosing {companyName}. We are leader in house-hold consumer product and ranked first in consumer satisfaction from last three years. We are offering our signature product {product} through Alexa. You can create new order or manage your existing order. Do you want to know more?

**Comment by shivamraspro** [comment]
This has been done and merged to development branch
